import { Inter } from "next/font/google";
// import "bootstrap/dist/css/bootstrap.min.css";
// import { useEffect } from "react";
// import Script from 'next/script';

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  // useEffect(() => {
  //   typeof document !== undefined ? require('bootstrap/dist/js/bootstrap.bundle.min.js') : null;
  // }, []);

  return (
    <html lang="en">
      <head>
        <script
              src="https://kit.fontawesome.com/23fe033599.js"
              crossOrigin="anonymous"
            ></script>        
        {/* Google Fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Limelight&display=swap" rel="stylesheet" />

      </head>
        
      <body className={inter.className}>
        {children}
        {/* <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" strategy="beforeInteractive" /> */}
        {/* <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script> */}
      </body>

    </html>
  );
}
